export default [
  {
    "id": "904cef3f-de1e-43b0-b1bf-15ac93ec45fa",
    "iid": 1,
    "name": "Broker1",
    "status": "active",
    "payment_terms_days": "30",
    "money_code_fee_cents": null,
    "quick_pay_fee_cents": null,
    "created_at": "2017-08-14T19:47:42.166Z",
    "updated_at": "2017-08-14T19:47:42.166Z",
    "miles_calculator": null,
    "miles_method_of_calculation": null,
    "state_id": null,
    "business_name": "Bizz",
    "contact_name": "Ivan",
    "contact_phone": "300012333",
    "address": "Address",
    "address_city": "Sacramento",
    "address_state": "State",
    "address_zip": "Zip",
    "billing_contact_name": "Contact Name",
    "billing_contact_phone": "Billing Contact Name",
    "billing_address": "Billing Address",
    "billing_address_city": "Billing Address City",
    "billing_address_state": "Billing Address State",
    "billing_address_zip": "900001",
    "duns_number": "12345",
    "ein_number": "1234",
    "logo_url": "url",
    "updated_by_user_id": null,
    "created_by_user_id": null,
    "billing_contact_email": "nelson@go-eka.com",
    "logo_full_url": "https://s3.amazonaws.com/ekadev/broker-logos/url"
  }
]
